<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1 (Total recall)

| Term | Brief description |
| :--- | :-- |
| Subsetting | Selecting a portion _or subset_ of a list or array.  |
| Indexing | Selecting a specific element in a list or array. |
| Slicing | Selecting a range of elements in a list or array. |
| Masking | Overlaying values in an array with their True/False values. _Only the True subset is seen_ |

## Exercise 2 (Show me the ‘odd’ letters)

In [19]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_1d = np_array_2d[:, 0]
np_array_1d = np_array_1d.astype(int)
np_array_1d%=2
my_mask = np_array_1d>0
print(np_array_2d[my_mask][:,1])

['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [ ]:
import numpy as np
my_array = np.array([[66, 50, 57, -1, -1],
                    [92, -1, 88, -1, -1],
                    [75, -1, -1, 76, -1],
                    [-1, 51, 87, -1, -1],
                    [71, -1, 67, -1, 69]])
my_array[my_array<50] = -1
my_array[my_array>50] = 1
my_array[my_array==50] = 0
print(my_array)

# Optional: if you want to shorten the code even more, you can simply write the following to create your mask
# np_array_1d = np_array_2d[:, 0]
# np_array_1d = np_array_1d.astype(int)
# my_mask = np_array_1d % 2 > 0

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
