<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [2]:
import numpy as np

#python lists:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#numpy arrays:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#dictionary:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [10]:
print(py_real_names[0])
print(py_super_names[0])
print(py_super_names[2])    # Forward indexing
print(py_super_names[-1])   # Reverse indexing (we need to know the length of the list beforehand)

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


## 1.3 Accessing data from a dictionary

In [11]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [7]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [8]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [ ]:
# 2D list
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [12]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
len(py_list_2d)

10

In [13]:
np_array_2d = np.array(py_list_2d)
len(np_array_2d)

10

In [16]:
# shape attribute of the numpy array
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [18]:
# arrays can only have a single data type, unlike lists
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

py_list

[1, 1.5, 'A']

In [19]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array + 10

array([11, 12, 13, 14, 15])

In [21]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [22]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

# adding lists causes them to grow, adding arrays is an element-wise operation
print(py_list_1 + py_list_2)
print(np_array_1 + np_array_2)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


## 2.5 Multiplying by a Number

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(py_list*2)
print(np_array*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


## 2.6 Squaring

In [26]:
np_array**2
# won't work for lists though

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [32]:
py_list == 3     # checks if the entire object py_list is equal to 3 (which is not true)

False

In [30]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [28]:
np_array == 3

array([False, False,  True, False, False])

In [29]:
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [ ]:
# base python functions:
print(sum(py_list))
print(max(py_list))
print(min(py_list))
# py_list.sum doesn't work

print(np_array.sum())
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.std())

# an operation on a list works on the whole list.
# In contrast, an operation on an array works on the individual elements of the array.

15
5
1
15
5
1
3.0
1.4142135623730951


## Footnotes