<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

subsetting: means to select<br>
indexing: picking a single element<br>
slicing: selecting a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np

In [ ]:
py_list=["a1", "b2", "c3", "d4", "e5","f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list
x[5:2:-1]
# if we slice with [i:j], the slice will start at i and end at j-1, giving j-i elements

['f6', 'e5', 'd4']

## 1.2 Arrays only | Subsetting by masking

In [ ]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask
# the t/f acts like a mask to allow only the True subset to be seen

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# show only those that are True
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [12]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [13]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [14]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [15]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [7]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

# position 4
print(py_list_2d[3])
np_array_2d[3]

[4, 'D']


array(['4', 'D'], dtype='<U21')

In [8]:
# first element at position 4
print(py_list_2d[3][0])
np_array_2d[3, 0]
# syntax for arrays use a single pair of square brackets []

4


np.str_('4')

In [9]:
# fist 3 elements
print(py_list_2d[:3])
np_array_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]


array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [11]:
print(py_list_2d[:3][0])   # it just gives the first of the list we get from py_list_2d[:3]
np_array_2d[:3, 0]

[1, 'A']


array(['1', '2', '3'], dtype='<U21')

In [12]:
print(py_list_2d[3:6][0])
np_array_2d[3:6, 0]

[4, 'D']


array(['4', '5', '6'], dtype='<U21')

In [13]:
# If you want ‘everything’ you just use ":"
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [ ]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [ ]:
x=[1]
x= x + [2]
x+= [3]
x.append(4)    # runs 1.5x faster than others
x

[1, 2, 3, 4]

In [22]:
# incorporating lists
x = [1, 2, 3]
x += [4, 5, 6]
x.extend([7, 8, 9])
x.append([10, 11, 12])
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, [10, 11, 12]]

# Some loose ends

## 1.5 Tuples

In [25]:
# touples are similar to lists except they use () and are immutable (can't be changed after creation)
a = (1,2,3)
print(a[0])

1


## 1.6 Be VERY careful when copying

In [ ]:
# of lists and arrays
x=[1, 2, 3]
y=x.copy()
z=x.copy()
# do NOT just equate y to x and z to x.

## Footnotes