<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

subsetting: means to select<br>
indexing: picking a single element<br>
slicing: selecting a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [8]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5","f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list
x[5:2:-1]
# if we slice with [i:j], the slice will start at i and end at j-1, giving j-i elements

['f6', 'e5', 'd4']

## 1.2 Arrays only | Subsetting by masking

In [ ]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask
# the t/f acts like a mask to allow only the True subset to be seen

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# show only those that are True
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [12]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [13]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [14]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [15]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes